# Generated by Django 3.2.1 on 2021-05-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('journal_content', models.TextField()),
                ('key_moments', models.TextField(blank=True, help_text="Seperate each moment with ','")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
