# Generated by Django 3.2.1 on 2021-05-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_journal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_content',
            field=models.TextField(),
        ),
    ]
