# Generated by Django 3.2.1 on 2021-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_journal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='key_moments',
            field=models.TextField(blank=True),
        ),
    ]
