# Generated by Django 3.2.1 on 2021-05-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journal_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
    ]
